// Bilingual copy strings. EN is canonical, PT mirrors structure.
window.COPY = {
  en: {
    nav: {
      docs: "Docs",
      framework: "Framework",
      github: "GitHub",
      install: "npx @axis-bootstrap/cli init",
    },
    hero: {
      eyebrow: "v{{VERSION}} · MIT · No runtime",
      headlineA: ["Your AI agent is", "losing context.", "Again."],
      headlineB: ["Spec. Harness.", "Continuity.", "In one line."],
      headlineC: ["Spec Kit solves", "1/3 of the problem.", "AXIS solves the 3."],
      sub: "The only open-source framework that unites multi-IDE, versioned harness, and memory-as-playbook — stack-agnostic, no runtime, in one command.",
      ctaPrimary: "npx @axis-bootstrap/cli init",
      ctaPrimaryHint: "Click to copy · MIT · No signup",
      ctaSecondary: "Read the framework",
      copied: "copied",
    },
    layers: {
      eyebrow: "// the three layers",
      title: "Three layers the literature treats separately. AXIS installs all three.",
      sub: "One line scaffolds the system. No daemon. No runtime. No call home.",
      cards: [
        {
          n: "01",
          name: "Spec",
          tag: "what the agent knows",
          body: "Short INSTRUCTIONS.md (100–180 lines) + skills with progressive disclosure. From 8–12k fixed tokens per session to 800–1,500 + on-demand.",
          tokens: ["INSTRUCTIONS.md", "skills/*", "progressive disclosure"],
        },
        {
          n: "02",
          name: "Harness",
          tag: "how the agent acts",
          body: "settings.json versioned in git with 25+ hook events. Each IDE gets its official format: .mdc for Cursor, .instructions.md for Copilot, hooks for Claude. One .ai/ folder generates all.",
          tokens: ["settings.json", "25+ hook events", ".mdc · .instructions.md"],
        },
        {
          n: "03",
          name: "Continuity",
          tag: "what survives between sessions",
          body: "STATE.md as a curated playbook (ACE principle, arXiv 2510.04618). Not a log. Not a diary. Context that evolves — session by session, decision by decision.",
          tokens: ["STATE.md", "Active Decisions", "ACE playbook"],
        },
      ],
    },
    tokens: {
      eyebrow: "// token economy",
      title: "From 8–12k fixed per session to 800–1,500 on-demand.",
      sub: "Cost down. Latency down. Same model.",
      before: "Before — monolithic CLAUDE.md",
      after: "After — AXIS progressive disclosure",
      fixed: "fixed",
      onDemand: "on-demand",
      perSession: "tokens per session",
    },
    ides: {
      eyebrow: "// multi-IDE",
      title: "One source. Every IDE. Official formats, not hacks.",
      sub: "Claude gets settings.json + hooks. Cursor gets .mdc rules. Copilot gets .instructions.md. All from one .ai/ folder.",
      source: ".ai/rules/*.md",
      sourceHint: "single source of truth",
      ides: [
        { name: "Claude Code", file: ".claude/rules/*.md + hooks" },
        { name: "Cursor", file: ".cursor/rules/*.mdc" },
        { name: "Copilot", file: ".github/instructions/*.instructions.md" },
        { name: "Windsurf", file: "AGENTS.md" },
        { name: "Codex / Others", file: "AGENTS.md (open standard)" },
      ],
    },
    terminal: {
      eyebrow: "// 10 seconds",
      title: "Bootstrap a project. Literally.",
      sub: "Watch what one line installs. Markdown and bash. No compiled code.",
      command: "npx @axis-bootstrap/cli init",
      lines: [
        { kind: "cmd", text: "npx @axis-bootstrap/cli init" },
        { kind: "info", text: "AXIS Bootstrap v{{VERSION}}" },
        { kind: "info", text: "Detected: Node 20.11 · git 2.43 · macOS" },
        { kind: "step", text: "phase 1/5 · discovery", detail: "spawning 5 Discoverer sub-agents" },
        { kind: "ok", text: "found 0 existing AXIS install" },
        { kind: "step", text: "phase 2/5 · scaffold", detail: "writing 27 files" },
        { kind: "ok", text: ".ai/ · .claude/ · .cursor/ · .github/" },
        { kind: "step", text: "phase 3/5 · harness", detail: "settings.json + hooks + .mdc rules + PR template" },
        { kind: "ok", text: "Claude hooks · Cursor .mdc · Copilot .instructions.md" },
        { kind: "step", text: "phase 4/5 · IDE formats", detail: "generating official format per IDE" },
        { kind: "ok", text: "5 IDEs · each in its native format" },
        { kind: "step", text: "phase 5/5 · state + cleanup", detail: "STATE.md + auto-remove bootstrap skill" },
        { kind: "ok", text: "ready · self-sufficient · open in any IDE" },
        { kind: "done", text: "done in 9.4s" },
      ],
    },
    research: {
      eyebrow: "// grounded in research",
      title: "Not opinion. Three papers and one benchmark.",
      items: [
        {
          tag: "Harness",
          stat: "top 30 → top 5",
          claim: "LangChain climbed Terminal Bench 2.0 by changing only the harness — same model.",
          source: "Augment Code · harness engineering",
        },
        {
          tag: "Reliability",
          stat: "20–40%",
          claim: "ReliabilityBench (jan/2026): pass@1 overstates reliability by 20–40%. Simple architectures win under stress.",
          source: "arXiv 2601.06112",
        },
        {
          tag: "Continuity",
          stat: "+10.6%",
          claim: "ACE — Agentic Context Engineering — gains 10.6% on agent benchmarks by treating context as curated playbook, not log.",
          source: "arXiv 2510.04618",
        },
      ],
    },
    cta: {
      eyebrow: "// or close the tab",
      lines: [
        "You'll read this. You'll close the tab.",
        "And next sprint you'll have the same 8,000-token CLAUDE.md.",
        "The same Cursor reading the October version.",
        "The same agent re-deciding what was decided three times before.",
      ],
      or: "or run one line now.",
      command: "npx @axis-bootstrap/cli init",
      hint: "MIT · No signup · 10 seconds",
    },
    footer: {
      tag: "AXIS Bootstrap",
      desc: "Spec. Harness. Continuity. Open source.",
      cols: [
        { h: "Install", items: ["CLI", "Quickstart", "Multi-IDE setup"] },
        { h: "Framework", items: ["Spec layer", "Harness layer", "Continuity (ACE)"] },
        { h: "Repo", items: ["GitHub", "Issues", "Releases"] },
      ],
      legal: "MIT · 2026 · The repo of AXIS is bootstrapped with AXIS.",
    },
  },

  pt: {
    nav: {
      docs: "Docs",
      framework: "Framework",
      github: "GitHub",
      install: "npx @axis-bootstrap/cli init",
    },
    hero: {
      eyebrow: "v{{VERSION}} · MIT · Sem runtime",
      headlineA: ["Seu agente de IA está", "perdendo contexto.", "De novo."],
      headlineB: ["Spec. Harness.", "Continuity.", "Em uma linha."],
      headlineC: ["Spec Kit resolve", "1/3 do problema.", "AXIS resolve os 3."],
      sub: "O único framework open-source que une multi-IDE, harness versionado e memória como playbook — stack-agnóstico, sem runtime, em uma linha de comando.",
      ctaPrimary: "npx @axis-bootstrap/cli init",
      ctaPrimaryHint: "Clique pra copiar · MIT · Sem cadastro",
      ctaSecondary: "Ler o framework",
      copied: "copiado",
    },
    layers: {
      eyebrow: "// as três camadas",
      title: "Três camadas que a literatura trata separadas. AXIS instala as três.",
      sub: "Uma linha scaffolda o sistema. Sem daemon. Sem runtime. Sem chamada pra servidor.",
      cards: [
        {
          n: "01",
          name: "Spec",
          tag: "o que o agente sabe",
          body: "INSTRUCTIONS.md curto (100–180 linhas) + skills com progressive disclosure. De 8–12k tokens fixos por sessão pra 800–1.500 + on-demand.",
          tokens: ["INSTRUCTIONS.md", "skills/*", "progressive disclosure"],
        },
        {
          n: "02",
          name: "Harness",
          tag: "como o agente age",
          body: "settings.json versionado em git com 25+ eventos de hook. Cada IDE recebe seu formato oficial: .mdc pro Cursor, .instructions.md pro Copilot, hooks pro Claude. Uma pasta .ai/ gera tudo.",
          tokens: ["settings.json", "25+ hook events", ".mdc · .instructions.md"],
        },
        {
          n: "03",
          name: "Continuity",
          tag: "o que sobrevive entre sessões",
          body: "STATE.md como playbook curado (princípio ACE, arXiv 2510.04618). Não é log. Não é diário. Contexto que evolui — sessão por sessão, decisão por decisão.",
          tokens: ["STATE.md", "Active Decisions", "ACE playbook"],
        },
      ],
    },
    tokens: {
      eyebrow: "// economia de tokens",
      title: "De 8–12k fixos por sessão pra 800–1.500 on-demand.",
      sub: "Custo cai. Latência cai. Mesmo modelo.",
      before: "Antes — CLAUDE.md monolítico",
      after: "Depois — progressive disclosure AXIS",
      fixed: "fixos",
      onDemand: "on-demand",
      perSession: "tokens por sessão",
    },
    ides: {
      eyebrow: "// multi-IDE",
      title: "Uma fonte. Toda IDE. Formatos oficiais, não gambiarras.",
      sub: "Claude recebe settings.json + hooks. Cursor recebe regras .mdc. Copilot recebe .instructions.md. Tudo de uma pasta .ai/.",
      source: ".ai/rules/*.md",
      sourceHint: "fonte única da verdade",
      ides: [
        { name: "Claude Code", file: ".claude/rules/*.md + hooks" },
        { name: "Cursor", file: ".cursor/rules/*.mdc" },
        { name: "Copilot", file: ".github/instructions/*.instructions.md" },
        { name: "Windsurf", file: "AGENTS.md" },
        { name: "Codex / Others", file: "AGENTS.md (padrão aberto)" },
      ],
    },
    terminal: {
      eyebrow: "// 10 segundos",
      title: "Bootstrap de um projeto. Literalmente.",
      sub: "Veja o que uma linha instala. Markdown e bash. Sem código compilado.",
      command: "npx @axis-bootstrap/cli init",
      lines: [
        { kind: "cmd", text: "npx @axis-bootstrap/cli init" },
        { kind: "info", text: "AXIS Bootstrap v{{VERSION}}" },
        { kind: "info", text: "Detectado: Node 20.11 · git 2.43 · macOS" },
        { kind: "step", text: "fase 1/5 · descoberta", detail: "spawnando 5 sub-agentes Discoverer" },
        { kind: "ok", text: "0 instalações AXIS existentes" },
        { kind: "step", text: "fase 2/5 · scaffold", detail: "escrevendo 27 arquivos" },
        { kind: "ok", text: ".ai/ · .claude/ · .cursor/ · .github/" },
        { kind: "step", text: "fase 3/5 · harness", detail: "settings.json + hooks + regras .mdc + PR template" },
        { kind: "ok", text: "Claude hooks · Cursor .mdc · Copilot .instructions.md" },
        { kind: "step", text: "fase 4/5 · formatos IDE", detail: "gerando formato oficial por IDE" },
        { kind: "ok", text: "5 IDEs · cada uma em seu formato nativo" },
        { kind: "step", text: "fase 5/5 · state + cleanup", detail: "STATE.md + auto-remove skill bootstrap" },
        { kind: "ok", text: "pronto · autossuficiente · abra em qualquer IDE" },
        { kind: "done", text: "done in 9.4s" },
      ],
    },
    research: {
      eyebrow: "// embasado em pesquisa",
      title: "Não é opinião. Três papers e um benchmark.",
      items: [
        {
          tag: "Harness",
          stat: "top 30 → top 5",
          claim: "LangChain subiu no Terminal Bench 2.0 trocando só o harness — mesmo modelo.",
          source: "Augment Code · harness engineering",
        },
        {
          tag: "Reliability",
          stat: "20–40%",
          claim: "ReliabilityBench (jan/2026): pass@1 superestima confiabilidade em 20–40%. Arquiteturas simples vencem sob stress.",
          source: "arXiv 2601.06112",
        },
        {
          tag: "Continuity",
          stat: "+10.6%",
          claim: "ACE — Agentic Context Engineering — ganha 10.6% em benchmarks de agentes tratando contexto como playbook curado.",
          source: "arXiv 2510.04618",
        },
      ],
    },
    cta: {
      eyebrow: "// ou feche a aba",
      lines: [
        "Você vai ler isso. Vai fechar a aba.",
        "E no próximo sprint vai ter o mesmo CLAUDE.md de 8.000 tokens.",
        "O mesmo Cursor lendo a versão de outubro.",
        "O mesmo agente decidindo de novo o que já tinha sido decidido três vezes.",
      ],
      or: "ou roda uma linha agora.",
      command: "npx @axis-bootstrap/cli init",
      hint: "MIT · Sem cadastro · 10 segundos",
    },
    footer: {
      tag: "AXIS Bootstrap",
      desc: "Spec. Harness. Continuity. Open source.",
      cols: [
        { h: "Instalação", items: ["CLI", "Quickstart", "Setup multi-IDE"] },
        { h: "Framework", items: ["Camada Spec", "Camada Harness", "Continuity (ACE)"] },
        { h: "Repo", items: ["GitHub", "Issues", "Releases"] },
      ],
      legal: "MIT · 2026 · O repo do AXIS é bootstrapado com AXIS.",
    },
  },
};
